### ISSUE TITLE
no editor in README.md

### ISSUE THREAD

**Issue by jxah** [jxah/my-private-story_v1#22]
remember #26

**Comment by escambron** [comment]
I will take a look.

**Comment by jxah** [comment]
don't forget @escambron porfavor.

**Comment by jxah** [comment]
No you did not @escambron i changed it to es? @escambron....

**Comment by escambron** [comment]
I will look to see .

**Comment by jxah** [comment]
sorry @escambron.

**Comment by jxah** [comment]
i'll do the rest @escambron.......ok?
